use_frameworks!

platform :ios, '12.0'
pod 'AFNetworking', '~> 4.0'

target 'AdFramework_Example' do
  pod 'AdFramework', :path => '../'

  target 'AdFramework_Tests' do
    inherit! :search_paths

    
  end
end
